login: &login
  adapter: mysql2
  host: localhost
  username: musicmunky 
  password: Pas9b53!


development:
  database: publify_dev
  <<: *login

test:
  database: publify_tests
  <<: *login

production:
  database: publify
  <<: *login
